//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransXLS2XML.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05747991")]
        public string TIN {
            get {
                return ((string)(this["TIN"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J13")]
        public string C_DOC {
            get {
                return ((string)(this["C_DOC"]));
            }
            set {
                this["C_DOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public string C_DOC_SUB {
            get {
                return ((string)(this["C_DOC_SUB"]));
            }
            set {
                this["C_DOC_SUB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string C_DOC_VER {
            get {
                return ((string)(this["C_DOC_VER"]));
            }
            set {
                this["C_DOC_VER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string C_DOC_TYPE {
            get {
                return ((string)(this["C_DOC_TYPE"]));
            }
            set {
                this["C_DOC_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string C_DOC_CNT {
            get {
                return ((string)(this["C_DOC_CNT"]));
            }
            set {
                this["C_DOC_CNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public string C_REG {
            get {
                return ((string)(this["C_REG"]));
            }
            set {
                this["C_REG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19")]
        public string C_RAJ {
            get {
                return ((string)(this["C_RAJ"]));
            }
            set {
                this["C_RAJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PERIOD_MONTH {
            get {
                return ((string)(this["PERIOD_MONTH"]));
            }
            set {
                this["PERIOD_MONTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PERIOD_TYPE {
            get {
                return ((string)(this["PERIOD_TYPE"]));
            }
            set {
                this["PERIOD_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020")]
        public string PERIOD_YEAR {
            get {
                return ((string)(this["PERIOD_YEAR"]));
            }
            set {
                this["PERIOD_YEAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1819")]
        public string C_STI_ORIG {
            get {
                return ((string)(this["C_STI_ORIG"]));
            }
            set {
                this["C_STI_ORIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string C_DOC_STAN {
            get {
                return ((string)(this["C_DOC_STAN"]));
            }
            set {
                this["C_DOC_STAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LINKED_DOCS {
            get {
                return ((string)(this["LINKED_DOCS"]));
            }
            set {
                this["LINKED_DOCS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09012020")]
        public string D_FILL {
            get {
                return ((string)(this["D_FILL"]));
            }
            set {
                this["D_FILL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MEDOC")]
        public string SOFTWARE {
            get {
                return ((string)(this["SOFTWARE"]));
            }
            set {
                this["SOFTWARE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ГОЛОВНЕ УПРАВЛІННЯ ДПС У СУМСЬКІЙ ОБЛАСТІ, УПРАВЛІННЯ У М.СУМАХ  (М. СУМИ)")]
        public string HSTI {
            get {
                return ((string)(this["HSTI"]));
            }
            set {
                this["HSTI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05747991")]
        public string HTIN {
            get {
                return ((string)(this["HTIN"]));
            }
            set {
                this["HTIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Акціонерне товариство \"Сумське машинобудівне науково-виробниче об\'єднання\"")]
        public string HNAME {
            get {
                return ((string)(this["HNAME"]));
            }
            set {
                this["HNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Лук`яненко Володимир Матвійович")]
        public string HBOS {
            get {
                return ((string)(this["HBOS"]));
            }
            set {
                this["HBOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09012020")]
        public string HFILL {
            get {
                return ((string)(this["HFILL"]));
            }
            set {
                this["HFILL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DOCNUMBER {
            get {
                return ((string)(this["DOCNUMBER"]));
            }
            set {
                this["DOCNUMBER"] = value;
            }
        }
    }
}
